apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::576161147066:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-124T6UMH1AM6E
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::576161147066:role/UdacityFlaskDeployCBKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-08T08:33:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1890"
  uid: f572b87f-89bd-498f-abb4-dd56cc2f7840
